En esta guía usted deberá realizar consultas SQL en un servidor virtual con PostgreSQL que contiene
datos de jugadores de fútbol. El esquema de los datos es el siguiente:

* $\color{green}{\textbf{jugadores}}(
    \color{blue}{\underline{\text{sofifa_id}}},
    \color{blue}{\text{nombre}},
    \color{blue}{\text{nombre_completo}},
    \color{blue}{\text{precio_eur}},
    \color{blue}{\text{edad}},
    \color{blue}{\text{nacimiento}},
    \color{blue}{\text{altura}},
    \color{blue}{\text{peso}},
    \color{blue}{\text{club_id}},
    \color{blue}{\text{liga_id}},
    \color{blue}{\text{numero}},
    \color{blue}{\text{fecha_ingreso}},
    \color{blue}{\text{nacionalidad_id}},
    \color{blue}{\text{pie}}
)$
* $\color{green}{\textbf{ligas}}(
    \color{blue}{\underline{\text{liga_id}}},
    \color{blue}{\text{nombre}}
)$
* $\color{green}{\textbf{clubes}}(
    \color{blue}{\underline{\text{club_id}}},
    \color{blue}{\text{nombre}},
    \color{blue}{\text{liga_id}}
)$
* $\color{green}{\textbf{nacionalidades}}(
    \color{blue}{\underline{\text{nacionalidad_id}}},
    \color{blue}{\text{nombre}}
)$
* $\color{green}{\textbf{posiciones}}(
    \color{blue}{\underline{\text{posicion_id}}},
    \color{blue}{\text{nombre}}
)$

* $\color{green}{\textbf{jugador_posiciones}}(
    \color{blue}{\underline{\text{jugador_id}}},
    \color{blue}{\underline{\text{posicion_id}}}
)$

Para iniciar el servidor virtual, instalar la base de datos postgres, y descargar los datos e importarlos, debe correr el siguiente bloque:

In [ ]:
# install
!apt update -qq
!apt install postgresql postgresql-contrib -y -qq
!service postgresql start
!sudo -u postgres psql -c "CREATE USER root WITH SUPERUSER PASSWORD 'root';"
!sudo -u postgres createdb guia -O root
# set connection
!wget -O /content/players_22.csv "https://drive.google.com/uc?export=download&id=1xXrtS05885IRuV7rVQLjtEnbvQLdqcyW"
!wget -O /content/poblar_tablas.sql "https://drive.google.com/uc?export=download&id=1-yWZBISuRbOnyCb0AWeUD_UR325FlcYU"
%load_ext sql
%config SqlMagic.feedback=False
%config SqlMagic.autopandas=True
%sql postgresql+psycopg2://root:root@localhost/guia
!psql -U root -d guia -f /content/poblar_tablas.sql

41 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
postgresql is already the newest version (14+238).
postgresql-contrib is already the newest version (14+238).
0 upgraded, 0 newly installed, 0 to remove and 41 not upgraded.
 * Starting PostgreSQL 14 database server
   ...done.
ERROR:  role "root" already exists
createdb: error: database creation failed: ERROR:  database "guia" already exists
--2025-09-24 17:31:15--  https://drive.google.com/uc?export=download&id=1xXrtS05885IRuV7rVQLjtEnbvQLdqcyW
Resolving drive.google.com (drive.google.com)... 172.217.12.14, 2607:f8b0:4025:803::200e
Connecting to drive.google.com (drive.google.com)|172.217.12.14|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1xXrtS05885IRuV7rVQLjtEnbvQLdqcyW&export=download [following]
--2025-09-24 17:31:16--  https://drive.usercontent.google.com/download?id=1xXrtS05885IRuV7rVQLjtEnbvQLdqcyW&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 172.217.164.1, 2607:f8b0:4025:803::2001
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|172.217.164.1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2720372 (2.6M) [application/octet-stream]
Saving to: ‘/content/players_22.csv’

/content/players_22 100%[===================>]   2.59M  --.-KB/s    in 0.1s

2025-09-24 17:31:17 (21.5 MB/s) - ‘/content/players_22.csv’ saved [2720372/2720372]

--2025-09-24 17:31:17--  https://drive.google.com/uc?export=download&id=1-yWZBISuRbOnyCb0AWeUD_UR325FlcYU
Resolving drive.google.com (drive.google.com)... 172.217.12.14, 2607:f8b0:4025:803::200e
Connecting to drive.google.com (drive.google.com)|172.217.12.14|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1-yWZBISuRbOnyCb0AWeUD_UR325FlcYU&export=download [following]
--2025-09-24 17:31:17--  https://drive.usercontent.google.com/download?id=1-yWZBISuRbOnyCb0AWeUD_UR325FlcYU&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 172.217.164.1, 2607:f8b0:4025:803::2001
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|172.217.164.1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1459 (1.4K) [application/octet-stream]
Saving to: ‘/content/poblar_tablas.sql’

/content/poblar_tab 100%[===================>]   1.42K  --.-KB/s    in 0s

2025-09-24 17:31:19 (17.6 MB/s) - ‘/content/poblar_tablas.sql’ saved [1459/1459]

The sql extension is already loaded. To reload it, use:
  %reload_ext sql
CREATE TABLE
COPY 19239
psql:/content/poblar_tablas.sql:24: NOTICE:  drop cascades to constraint jugador_posiciones_jugador_id_fkey on table jugador_posiciones
DROP TABLE
CREATE TABLE
INSERT 0 19239

Ejecute la siguiente consulta para probar que todo ande bien:

In [ ]:
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

In [ ]:
%sql SELECT * FROM datos LIMIT 5;

 * postgresql+psycopg2://root:***@localhost/guia

,sofifa_id,nombre,nombre_completo,posiciones,precio_eur,edad,nacimiento,altura,peso,club,liga,numero,fecha_ingreso,nacionalidad,pie
0,158023,L. Messi,Lionel Andrés Messi Cuccittini,"RW, ST, CF",78000000.0,34,1987-06-24,170,72,Paris Saint-Germain,French Ligue 1,30,2021-08-10,Argentina,Left
1,188545,R. Lewandowski,Robert Lewandowski,ST,119500000.0,32,1988-08-21,185,81,FC Bayern München,German 1. Bundesliga,9,2014-07-01,Poland,Right
2,20801,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",45000000.0,36,1985-02-05,187,83,Manchester United,English Premier League,7,2021-08-27,Portugal,Right
3,190871,Neymar Jr,Neymar da Silva Santos Júnior,"LW, CAM",129000000.0,29,1992-02-05,175,68,Paris Saint-Germain,French Ligue 1,10,2017-08-03,Brazil,Right
4,192985,K. De Bruyne,Kevin De Bruyne,"CM, CAM",125500000.0,30,1991-06-28,181,70,Manchester City,English Premier League,17,2015-08-30,Belgium,Right

Para ejecutar consultas multi-lineas use el tag %%sql:

In [ ]:
%%sql
SELECT *
FROM datos
where nombre ilike '%Messi%';

 * postgresql+psycopg2://root:***@localhost/guia

,sofifa_id,nombre,nombre_completo,posiciones,precio_eur,edad,nacimiento,altura,peso,club,liga,numero,fecha_ingreso,nacionalidad,pie
0,158023,L. Messi,Lionel Andrés Messi Cuccittini,"RW, ST, CF",78000000.0,34,1987-06-24,170,72,Paris Saint-Germain,French Ligue 1,30,2021-08-10,Argentina,Left
1,240938,Junior Messias,Junior Walter Messias,"CAM, CF, CM",4100000.0,30,1991-05-13,179,70,AC Milan,Italian Serie A,30,None,Brazil,Left

# SQL - Modificaciones

Crear tabla ligas con liga_id(PK) y nombre.

In [ ]:
%%sql
DROP TABLE IF EXISTS ligas CASCADE;
CREATE TABLE ligas (
    liga_id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) UNIQUE NOT NULL
);

-- llenar tabla ligas
INSERT INTO ligas (nombre)
SELECT DISTINCT liga
FROM datos
WHERE liga IS NOT NULL;

SELECT *
FROM ligas
LIMIT 5;

 * postgresql+psycopg2://root:***@localhost/guia

   liga_id                         nombre
0        1              Turkish Süper Lig
1        2             Ecuadorian Serie A
2        3  Japanese J. League Division 1
3        4    Chilian Campeonato Nacional
4        5        English National League

Crear tabla clubes con club_id(PK), nombre y liga_id(FK).

In [ ]:
%%sql
DROP TABLE IF EXISTS clubes CASCADE;
CREATE TABLE clubes (
    club_id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) UNIQUE NOT NULL,
    liga_id INT REFERENCES ligas(liga_id)
);

-- llenar tabla clubes
INSERT INTO clubes (nombre, liga_id)
SELECT DISTINCT d.club, l.liga_id
FROM datos d
JOIN ligas l ON d.liga = l.nombre
WHERE d.club IS NOT NULL;

SELECT *
FROM clubes
LIMIT 5;

 * postgresql+psycopg2://root:***@localhost/guia

   club_id                   nombre  liga_id
0        1         Panathinaikos FC       16
1        2  Independiente del Valle        2
2        3                   Al Tai       41
3        4   St. Patrick's Athletic       33
4        5                Morecambe       26

Crear tabla nacionalidades con nacionalidad_id (PK) y nombre.

In [ ]:
%%sql
DROP TABLE IF EXISTS nacionalidades CASCADE;
CREATE TABLE nacionalidades (
    nacionalidad_id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) UNIQUE NOT NULL
);

-- llenar tabla nacionalidades
INSERT INTO nacionalidades (nombre)
SELECT DISTINCT nacionalidad
FROM datos
WHERE nacionalidad IS NOT NULL;

SELECT *
FROM nacionalidades
LIMIT 5;

 * postgresql+psycopg2://root:***@localhost/guia

   nacionalidad_id          nombre
0                1       Indonesia
1                2       Venezuela
2                3        Cameroon
3                4      Luxembourg
4                5  Czech Republic

Crear la tabla jugadores.

In [ ]:
%%sql
DROP TABLE IF EXISTS jugadores CASCADE;
CREATE TABLE jugadores (
    sofifa_id INTEGER PRIMARY KEY,
    nombre TEXT,
    nombre_completo TEXT,
    precio_eur NUMERIC,
    edad INTEGER,
    nacimiento DATE,
    altura INTEGER,
    peso INTEGER,
    club_id INT REFERENCES clubes(club_id),
    liga_id INT REFERENCES ligas(liga_id),
    numero INTEGER,
    fecha_ingreso DATE,
    nacionalidad_id INT REFERENCES nacionalidades(nacionalidad_id),
    pie TEXT
);


INSERT INTO jugadores (sofifa_id, nombre, nombre_completo, precio_eur, edad, nacimiento, altura, peso, club_id, liga_id, numero, fecha_ingreso, nacionalidad_id, pie)
SELECT d.sofifa_id,
       d.nombre,
       d.nombre_completo,
       d.precio_eur,
       d.edad,
       d.nacimiento,
       d.altura,
       d.peso,
       c.club_id,
       l.liga_id,
       d.numero,
       d.fecha_ingreso,
       n.nacionalidad_id,
       d.pie
FROM datos d
LEFT JOIN clubes c ON d.club = c.nombre
LEFT JOIN ligas l ON d.liga = l.nombre
LEFT JOIN nacionalidades n ON d.nacionalidad = n.nombre;

SELECT *
FROM jugadores
LIMIT 5;

 * postgresql+psycopg2://root:***@localhost/guia

,sofifa_id,nombre,nombre_completo,precio_eur,edad,nacimiento,altura,peso,club_id,liga_id,numero,fecha_ingreso,nacionalidad_id,pie
0,158023,L. Messi,Lionel Andrés Messi Cuccittini,78000000.0,34,1987-06-24,170,72,646,17,30,2021-08-10,91,Left
1,188545,R. Lewandowski,Robert Lewandowski,119500000.0,32,1988-08-21,185,81,93,53,9,2014-07-01,156,Right
2,20801,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,45000000.0,36,1985-02-05,187,83,103,10,7,2021-08-27,15,Right
3,190871,Neymar Jr,Neymar da Silva Santos Júnior,129000000.0,29,1992-02-05,175,68,646,17,10,2017-08-03,133,Right
4,192985,K. De Bruyne,Kevin De Bruyne,125500000.0,30,1991-06-28,181,70,329,10,17,2015-08-30,72,Right

Crear tabla posiciones.

In [ ]:
%%sql
DROP TABLE IF EXISTS posiciones CASCADE;
CREATE TABLE posiciones (
    posicion_id SERIAL PRIMARY KEY,
    nombre VARCHAR(10) UNIQUE NOT NULL
);

-- llenar posiciones
INSERT INTO posiciones (nombre)
SELECT DISTINCT unnest(string_to_array(posiciones, ', ')) AS pos
FROM datos
WHERE posiciones IS NOT NULL;

SELECT *
FROM posiciones
LIMIT 5;

 * postgresql+psycopg2://root:***@localhost/guia

   posicion_id nombre
0            1     CB
1            2     LB
2            3     RW
3            4     RB
4            5    CAM

Relacionar jugadores y posiciones.

In [ ]:
%%sql
DROP TABLE IF EXISTS jugador_posiciones CASCADE;
CREATE TABLE jugador_posiciones (
    jugador_id INT,
    posicion_id INT,
    PRIMARY KEY (jugador_id, posicion_id),
    FOREIGN KEY (jugador_id) REFERENCES jugadores(sofifa_id),
    FOREIGN KEY (posicion_id) REFERENCES posiciones(posicion_id)
);

INSERT INTO jugador_posiciones (jugador_id, posicion_id)
SELECT j.sofifa_id, p.posicion_id
FROM datos d
JOIN jugadores j ON d.sofifa_id = j.sofifa_id
JOIN posiciones p ON p.nombre = ANY(string_to_array(d.posiciones, ', '))
WHERE d.posiciones IS NOT NULL;

SELECT *
FROM jugador_posiciones
LIMIT 5;

 * postgresql+psycopg2://root:***@localhost/guia

   jugador_id  posicion_id
0      158023           10
1      158023            3
2      158023           11
3      188545           11
4       20801            7

Ahora, debe diseñar las consultas que resuelvan las siguientes preguntas usando los operadores vistos en clases.

#SQL - Consultas
## Pregunta 1
1a. TOP 10 JUGADORES MAS CAROS: muestra en orden descendiente los jugadores en los cuales su precio sea mayor.

In [1]:
%%sql

UsageError: Cell magic `%%sql` not found.

1b. TOP 10 CLUBES MAS CAROS: muestra en orden descendiente los clubes en los cuales la sumatoria de los precios de sus jugadores sea mayor.

In [2]:
%%sql

UsageError: Cell magic `%%sql` not found.

## Pregunta 2
2. TOP 10 DIAS QUE MAS GANACIA A GENERADO: muestra en orden descendiente los dias en los cuales la suma total de los precios de los jugadores nacidos ese dia sea mayor.

In [3]:
%%sql

UsageError: Cell magic `%%sql` not found.

# Pregunta 3
3. TOP 25 JUGADORES QUE JUEGAN MAS DE UNA POSICION: muestra en orden descendiente los 25 mejores jugadores (segun precio de mercado) que jueguen mas de una posicion, en caso de empate compara por edad ascendente.

In [4]:
%%sql

UsageError: Cell magic `%%sql` not found.

## Pregunta 4
4. TOP 12 MESES CON MAS JUGADORES: muestra en orden descendiente los meses en los cuales mas jugadores han nacido.

In [5]:
%%sql

UsageError: Cell magic `%%sql` not found.

## Pregunta 5
5. EQUIPOS CON MAS JUGADORES NACIDOS EL MISMO MES: muestra el top 10 de equipos donde mas jugadores esten de cumpleaños el mismo mes.

In [6]:
%%sql

UsageError: Cell magic `%%sql` not found.

## Pregunta 6
6. CLUBES CON MAYOR VALOR Y EDAD PROMEDIO: muestra el top 10 de equipos con mercado y edad mas altos.

In [7]:
%%sql

UsageError: Cell magic `%%sql` not found.